version: 2
mergeable:
  - when: schedule.repository
    validate:
      - do: stale
        days: 20
        type: issues
    filter:
      - do: repository
        name:
          or:
            - must_include:
              regex: 'pi-hole'
            - must_include:
              regex: 'adminLTE'
    pass:
      - do: comment
        payload:
          body: This issue has not been updated in 20 or more days. Is this item still relevant?
