version: 2
mergeable:
  - when: schedule.repository
    validate:
      - do: stale
        days: 20
        type: issues
      - do: repository
        name:
          or:
            - must_include:
              regex: 'pi-hole'
            - must_include:
              regex: 'adminLTE'
    pass:
      - do: comment
        payload:
          body: This item is 20 days or more old. Is this item still relevant?
