name: Delete old container images

on:
  workflow_dispatch:


jobs:
  clean-ghcr:
    name: Prune Untagged
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [ftl-build, pihole, docker-pi-hole-base]
    steps:
      - 
        name: Prune
        uses: vlaurin/action-ghcr-prune@main
        with:
          token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
          organization: pi-hole
          container: ${{ matrix.container }}
          dry-run: false
          untagged: true